/**
 * Scans Day- Morse* folders for slide decks and syncs them into the Next.js app.
 *
 * Source of truth (you edit these):
 *   Day-01/slides/*.html
 *   Day-02/slides/*.html
 *   Day-04/slides/*.html  <- just add this folder + push, Vercel picks it up
 *
 * Generated outputs (do not edit):
 *   public/slides/day01.html, day02.html, ...
 *   src/lib/days.generated.ts  (route manifest)
 *
 * Runs automatically via `predev` / `prebuild`, and therefore on every
 * Vercel deployment. `npm run sync:slides` runs it manually.
 */
import { copyFileSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC_DIR = join(ROOT, "public", "slides");
const GENERATED = join(ROOT, "src", "lib", "days.generated.ts");

function listDayDirs() {
  return readdirSync(ROOT)
    .filter((name) => /^day-\d+$/i.test(name))
    .filter((name) => {
      try {
        return statSync(join(ROOT, name)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort((a, b) =>
      a.toLowerCase().localeCompare(b.toLowerCase(), undefined, { numeric: true })
    );
}

function listSlides(dayDir) {
  const slidesDir = join(ROOT, dayDir, "slides");
  try {
    if (!statSync(slidesDir).isDirectory()) return [];
  } catch {
    return [];
  }
  return readdirSync(slidesDir)
    .filter((f) => f.toLowerCase().endsWith(".html"))
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase(), undefined, { numeric: true }));
}

function extractTitle(html) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  if (!m) return null;
  return m[1].replace(/&amp;/g, "&").replace(/&#39;/g, "'").replace(/&quot;/g, '"').trim();
}

function splitTitle(fullTitle, fallbackNum) {
  // "Day 01 — Python Foundations & Virtual Environments" -> short title after dash
  const m = fullTitle.match(/^day\s*\d+\s*[—–-]\s*(.+)$/i);
  if (m) return m[1].trim();
  return fullTitle || `Day ${fallbackNum}`;
}

function iconFor(text) {
  const t = text.toLowerCase();
  if (t.includes("git")) return "git";
  if (t.includes("number") || t.includes("string") || t.includes("type")) return "code";
  if (t.includes("virtual") || t.includes("environment") || t.includes("setup")) return "terminal";
  if (t.includes("python")) return "terminal";
  return "book";
}

const dayDirs = listDayDirs();
mkdirSync(PUBLIC_DIR, { recursive: true });

const days = [];
for (const dir of dayDirs) {
  const num = parseInt(dir.match(/(\d+)/)[1], 10);
  const id = `day${String(num).padStart(2, "0")}`;
  const slides = listSlides(dir);
  if (slides.length === 0) {
    console.warn(`[sync:slides] ${dir}: no .html files in slides/ — skipped`);
    continue;
  }
  const srcFile = slides[0];
  if (slides.length > 1) {
    console.warn(
      `[sync:slides] ${dir}: ${slides.length} html files found, using first (${srcFile})`
    );
  }
  const html = readFileSync(join(ROOT, dir, "slides", srcFile), "utf8");
  const fullTitle = extractTitle(html) ?? `Day ${String(num).padStart(2, "0")}`;
  const title = splitTitle(fullTitle, num);
  const destFile = `${id}.html`;
  copyFileSync(join(ROOT, dir, "slides", srcFile), join(PUBLIC_DIR, destFile));

  days.push({
    id,
    num,
    dir,
    title,
    fullTitle,
    file: `/slides/${destFile}`,
    route: `/${id}`,
    icon: iconFor(`${title} ${fullTitle}`),
  });
}

// Remove stale public copies (e.g. Day deleted)
const wanted = new Set(days.map((d) => `${d.id}.html`));
for (const f of readdirSync(PUBLIC_DIR)) {
  if (f.toLowerCase().endsWith(".html") && !wanted.has(f)) {
    const { unlinkSync } = await import("node:fs");
    unlinkSync(join(PUBLIC_DIR, f));
    console.warn(`[sync:slides] removed stale public/slides/${f}`);
  }
}

days.sort((a, b) => a.num - b.num);

const out = `// AUTO-GENERATED by scripts/sync-slides.mjs — do not edit.
// Source of truth: Day-*/slides/*.html
export type DayIcon = "terminal" | "git" | "code" | "book";
export interface DayMeta {
  id: string;
  num: number;
  dir: string;
  title: string;
  fullTitle: string;
  file: string;
  route: string;
  icon: DayIcon;
}
export const DAYS: DayMeta[] = ${JSON.stringify(days, null, 2)};
`;

mkdirSync(dirname(GENERATED), { recursive: true });
writeFileSync(GENERATED, out);
console.log(`[sync:slides] ${days.length} day(s): ${days.map((d) => d.id).join(", ") || "none"}`);
